---
security:
  oauth2:
    client:
      clientId: 0oag0tgbgsQTJKwdK0h7
      clientSecret: 3NXjxEWPcke5FuQAVE-miVdJ8yqGqhXg-mLKQhZm
    resource:
      tokenInfoUri: "https://dev-562925.oktapreview.com/oauth2/default/v1/introspect"
