---
example:
  baseUrl: "http://localhost:8080"
  oauth2:
    client:
      accessTokenUri: "https://dev-562925.oktapreview.com/oauth2/default/v1//token"
      clientId: 0oag0tgbgsQTJKwdK0h7
      clientSecret: 3NXjxEWPcke5FuQAVE-miVdJ8yqGqhXg-mLKQhZm
      grantType: client_credentials
      scope: custom_mod
